### ISSUE TITLE
gpl1 has been removed from nixpkgs

### ISSUE THREAD

**Issue by mweinelt** [jtojnar/nixpkgs-hammering#132]
https://github.com/nixos/nixpkgs/commit/870d6f4a98f19374d1188006574b8d55ca4a6547

This makes nixpkgs-hammering fail like this:

```
❯ nix shell -f https://github.com/jtojnar/nixpkgs-hammering/archive/master.tar.gz -c nixpkgs-hammer kea
error: attribute 'gpl1' missing

       at /nix/store/r0jiswp9dhxnivy0aj2ikyvqnplm67lq-nixpkgs-hammering/overlays/unclear-gpl.nix:23:25:

           22|         name = "unclear-gpl";
           23|         cond = lib.elem lib.licenses.${license} (lib.toList (drvArgs.meta.license or []));
             |                         ^
           24|         msg = ''
       Did you mean one of gpl2, gpl3, agpl3, cpl10 or epl10?
(use '--show-trace' to show detailed location information)
Traceback (most recent call last):
  File "/nix/store/r0jiswp9dhxnivy0aj2ikyvqnplm67lq-nixpkgs-hammering/bin/.nixpkgs-hammer-wrapped", line 410, in <module>
    main(args)
  File "/nix/store/r0jiswp9dhxnivy0aj2ikyvqnplm67lq-nixpkgs-hammering/bin/.nixpkgs-hammer-wrapped", line 331, in main
    overlay_data = nix_eval_json(all_messages_nix, args.show_trace)
  File "/nix/store/r0jiswp9dhxnivy0aj2ikyvqnplm67lq-nixpkgs-hammering/bin/.nixpkgs-hammer-wrapped", line 136, in nix_eval_json
    json_text = subprocess.check_output(args, text=True, input=expr)
  File "/nix/store/xf1k5k05vg3zn7dfcpfh1qa7ga48hi3m-python3-3.10.6/lib/python3.10/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/nix/store/xf1k5k05vg3zn7dfcpfh1qa7ga48hi3m-python3-3.10.6/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['nix-instantiate', '--strict', '--json', '--eval', '-']' returned non-zero exit status 1.

**Comment by jtojnar** [comment]
Thanks for reporting, should be fixed.
