### ISSUE TITLE
Incorrectly assuming echo is on the PATH

### ISSUE THREAD

**Issue by rmcgibbo** [jtojnar/nixpkgs-hammering#22]
:sigh: It looks like this is a bug I introduced in the last PR. It's pretty esoteric though -- when running in a very locked down environment without anything extra on the PATH, it looks like we fail to find `echo`.

I suppose I should add coreutils to the PATH [here](https://github.com/jtojnar/nixpkgs-hammering/blob/master/flake.nix#L49) unless you have a better idea.
```
error: --- SysError --- nix
cannot run command 'echo' '/home/worker/.cache/nixpkgs-review/pr-111522/nixpkgs/pkgs/servers/klipper/default.nix': No such file or directory
Traceback (most recent call last):
  File "/nix/store/asxwrspsg1sa1zzijg5w38iwjnsybj02-nixpkgs-hammer/bin/.nixpkgs-hammer-wrapped", line 268, in <module>
    main(args)
  File "/nix/store/asxwrspsg1sa1zzijg5w38iwjnsybj02-nixpkgs-hammer/bin/.nixpkgs-hammer-wrapped", line 207, in main
    all_ast_check_messages = ast_checks(args.nix_file, args.attr_paths, args.excluded_rules)
  File "/nix/store/asxwrspsg1sa1zzijg5w38iwjnsybj02-nixpkgs-hammer/bin/.nixpkgs-hammer-wrapped", line 38, in ast_checks
    file = attr_to_file_path(attr, nix_file)
  File "/nix/store/asxwrspsg1sa1zzijg5w38iwjnsybj02-nixpkgs-hammer/bin/.nixpkgs-hammer-wrapped", line 25, in attr_to_file_path
    proc = subprocess.run(
  File "/nix/store/akrgx3370c6bl8akpd3j75hzqclicdl4-python3-3.8.7/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['nix', 'edit', '--experimental-features', 'nix-command', '-f', PosixPath('/home/worker/.cache/nixpkgs-review/pr-111522/nixpkgs'), 'klipper']' returned non-zero exit status 1.
```

**Comment by jtojnar** [comment]
Alternative would be just evaluating `drv.meta.position` ourselves. But adding ¿coreutils? to `PATH` sounds like a good quick fix.
