### ISSUE TITLE
'Argument list too long'

### ISSUE THREAD

**Issue by rmcgibbo** [jtojnar/nixpkgs-hammering#39]
I'm probably playing with fire by even attempting this, but an invocation like this: https://gist.githubusercontent.com/rmcgibbo/bd6aea3a3ce4f38fc1f5de29ef8a65b6/raw/ab09ff82b788e6ee438d25ae626082c099d43fd9/gistfile1.txt

fails with the following traceback

```
Traceback (most recent call last):
  File "/nix/store/490ga3515nfk5w5a9r9dbck3da7jhl3a-nixpkgs-hammer/bin/.nixpkgs-hammer-wrapped", line 291, in <module>
    main(args)
  File "/nix/store/490ga3515nfk5w5a9r9dbck3da7jhl3a-nixpkgs-hammer/bin/.nixpkgs-hammer-wrapped", line 229, in main
    all_overlay_messages = nix_eval_json(all_messages_nix, args.show_trace)
  File "/nix/store/490ga3515nfk5w5a9r9dbck3da7jhl3a-nixpkgs-hammer/bin/.nixpkgs-hammer-wrapped", line 81, in nix_eval_json
    result = subprocess.check_output(
  File "/nix/store/wkw6fsjasr7jbbrlakxxpbiapa8hws42-python3-3.8.7/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/nix/store/wkw6fsjasr7jbbrlakxxpbiapa8hws42-python3-3.8.7/lib/python3.8/subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/nix/store/wkw6fsjasr7jbbrlakxxpbiapa8hws42-python3-3.8.7/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/nix/store/wkw6fsjasr7jbbrlakxxpbiapa8hws42-python3-3.8.7/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 7] Argument list too long: 'nix-instantiate'
```

Perhaps we could pass the expression to nix-instantiate with a tempfile or pipe instead.

**Comment by jtojnar** [comment]
Yeah, I used tempdir initially but then managed to [simplify it](https://github.com/jtojnar/nixpkgs-hammering/commit/04f1c3d5aba6f8d35496d01c029842ec542079d3), which allowed me to pass the argument directly.

I guess using a tempfile or tempdir is inevitable though.
