### ISSUE TITLE
nixpkgs-hammer crashes with ccacheStdenv

### ISSUE THREAD

**Issue by SuperSandro2000** [jtojnar/nixpkgs-hammering#52]
nixpkgs-hammer ccacheStdenv
```
error: --- EvalError ------------------------------------------------------------------------------------------------------------------------------------------------------- nix-instantiateat: (11:17) from stdin

    10|             if result.success && result.value != null then
    11|                 result.value.meta.position
      |                 ^
    12|             else

attribute 'position' missing
(use '--show-trace' to show detailed location information)
Traceback (most recent call last):
  File "/nix/store/wqh9kvilxk2fw6xp8ps87rdcv0ggqj8b-nixpkgs-hammer/bin/.nixpkgs-hammer-wrapped", line 295, in <module>
    main(args)
  File "/nix/store/wqh9kvilxk2fw6xp8ps87rdcv0ggqj8b-nixpkgs-hammer/bin/.nixpkgs-hammer-wrapped", line 223, in main
    overlay_data = nix_eval_json(all_messages_nix, args.show_trace)
  File "/nix/store/wqh9kvilxk2fw6xp8ps87rdcv0ggqj8b-nixpkgs-hammer/bin/.nixpkgs-hammer-wrapped", line 65, in nix_eval_json
    result = subprocess.check_output(
  File "/nix/store/wkw6fsjasr7jbbrlakxxpbiapa8hws42-python3-3.8.7/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/nix/store/wkw6fsjasr7jbbrlakxxpbiapa8hws42-python3-3.8.7/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['nix-instantiate', '--strict', '--json', '--eval', '-']' returned non-zero exit status 1.
```

**Comment by rmcgibbo** [comment]
Thanks, Sandro.
