### ISSUE TITLE
Error when running in https://github.com/NixOS/nixpkgs/pull/112625

### ISSUE THREAD

**Issue by SuperSandro2000** [jtojnar/nixpkgs-hammering#54]
I've run hammering on https://github.com/NixOS/nixpkgs/pull/112625 (6d2451626d6aa17cec17db1ee8f26835698ab26d) in nixpkgs-review and got the following error: It does not happen on master and I am not sure whats going on here.

nixpkgs-hammer --exclude attribute-ordering --exclude explicit-phases python38Packages.aws-adfs
```
error: --- TypeError ------------------------------------------------------------------------------------------------------------------------------------------------------- nix-instantiateat: (18:69) in file: /nix/store/0b124ysqxb9bg3r5zfwdzflf44gvm54h-nixpkgs-hammer/overlays/python-include-tests.nix

    17|           hasDoCheckFalse = (drvArgs ? doCheck) && (drvArgs.doCheck == false);
    18|           hasPytestCheckHook = drvArgs ? checkInputs && lib.any (n: n.name == "pytest-check-hook") drvArgs.checkInputs;
      |                                                                     ^
    19|           hasPythonImportsCheck = drvArgs ? pythonImportsCheck;

value is null while a set was expected
(use '--show-trace' to show detailed location information)
Traceback (most recent call last):
  File "/nix/store/0b124ysqxb9bg3r5zfwdzflf44gvm54h-nixpkgs-hammer/bin/.nixpkgs-hammer-wrapped", line 295, in <module>
    main(args)
  File "/nix/store/0b124ysqxb9bg3r5zfwdzflf44gvm54h-nixpkgs-hammer/bin/.nixpkgs-hammer-wrapped", line 223, in main
    overlay_data = nix_eval_json(all_messages_nix, args.show_trace)
  File "/nix/store/0b124ysqxb9bg3r5zfwdzflf44gvm54h-nixpkgs-hammer/bin/.nixpkgs-hammer-wrapped", line 65, in nix_eval_json
    result = subprocess.check_output(
  File "/nix/store/4jf77mhzlwhk92rh32ba0qff0nc7vj3i-python3-3.8.7/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/nix/store/4jf77mhzlwhk92rh32ba0qff0nc7vj3i-python3-3.8.7/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['nix-instantiate', '--strict', '--json', '--eval', '-']' returned non-zero exit status 1.
```

**Comment by jtojnar** [comment]
That means a package has `null` in `checkInputs`. Which is discouraged in nixpkgs but it the checks should handle it. I cannot reproduce with  https://github.com/NixOS/nixpkgs/pull/112625 (746c3368eee at the time I checked it out) nor with https://github.com/fabaff/nixpkgs/archive/6d2451626d6aa17cec17db1ee8f26835698ab26d.tar.gz but the following patch can reproduce it:

```patch
diff --git a/pkgs/development/python-modules/aws-adfs/default.nix b/pkgs/development/python-modules/aws-adfs/default.nix
index ce4c6f78926..1f381f62901 100644
--- a/pkgs/development/python-modules/aws-adfs/default.nix
+++ b/pkgs/development/python-modules/aws-adfs/default.nix
@@ -23,7 +23,7 @@ buildPythonPackage rec {
   # Required for python3 tests, along with glibcLocales
   LC_ALL = "en_US.UTF-8";
 
-  checkInputs = [ glibcLocales pytest pytestrunner pytestcov mock ];
+  checkInputs = [ glibcLocales pytest pytestrunner pytestcov mock null ];
   propagatedBuildInputs = [ botocore lxml requests requests-kerberos click configparser fido2 ];
 
   meta = with lib; {
```
