### ISSUE TITLE
TypeError in no-flags-spaces

### ISSUE THREAD

**Issue by rmcgibbo** [jtojnar/nixpkgs-hammering#68]
At 5a81aec998b6c75e9ed84016344f3772f32e262e, with nixpkgs 71e0a6fb1d06f8f04fe07a8b9c763ded8370f5cc

```
$ nixpkgs-hammer -f . --json  php73Extensions.xml
error: --- TypeError ------------------------------------------------------------------------------------------------------------- nix-instantiate
at: (25:24) in file: /nix/store/2wp7pwx62bgpyazjl01p6kgd116961qx-nixpkgs-hammer/overlays/no-flags-spaces.nix

    24| 
    25|   containsSpace = str: builtins.match ".*[[:space:]].*" str != null;
      |                        ^
    26| 

value is a list while a string was expected
(use '--show-trace' to show detailed location information)
Traceback (most recent call last):
  File "/nix/store/2wp7pwx62bgpyazjl01p6kgd116961qx-nixpkgs-hammer/bin/.nixpkgs-hammer-wrapped", line 295, in <module>
    main(args)
  File "/nix/store/2wp7pwx62bgpyazjl01p6kgd116961qx-nixpkgs-hammer/bin/.nixpkgs-hammer-wrapped", line 223, in main
    overlay_data = nix_eval_json(all_messages_nix, args.show_trace)
  File "/nix/store/2wp7pwx62bgpyazjl01p6kgd116961qx-nixpkgs-hammer/bin/.nixpkgs-hammer-wrapped", line 65, in nix_eval_json
    result = subprocess.check_output(
  File "/nix/store/wkw6fsjasr7jbbrlakxxpbiapa8hws42-python3-3.8.7/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/nix/store/wkw6fsjasr7jbbrlakxxpbiapa8hws42-python3-3.8.7/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['nix-instantiate', '--strict', '--json', '--eval', '-']' returned non-zero exit status 1.
```

**Comment by rmcgibbo** [comment]
I think this is a [bug in php-packages.nix here](https://github.com/NixOS/nixpkgs/blob/173edd9547c65c31e1a5c8c26fe4d5799e01ef47/pkgs/top-level/php-packages.nix#L269-L271).

IIUC, this evaluates to `configureFlags =  [ "--enable-simplexml"  [ "--with-libxml-dir=${libxml2.dev}" ] ];` (nested list).

Do we need to add another layer of checks that do type-checking...

**Comment by jtojnar** [comment]
Thanks for pointing that out. `lib.optional` is IMO more trouble than it is worth. https://github.com/NixOS/nixpkgs/pull/114210 will fix that for PHP packages.

Yeah, type checking would be good. Maybe just define the options using NixOS module system?
